name: Build and Deploy (Spring Boot + React)

on:
  push:
    branches:
      - master # master 브랜치에 push될 때 실행
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. GitHub에서 코드 체크아웃 -> 현재 커밋의 코드 가져옴
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Spring Boot 빌드 (Maven)
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build Spring Boot
      run: |
        cd backend
        mvn clean package 

    # 3. React 빌드 (npm)
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Build React
      run: |
        cd frontend
        npm install
        npm run build

    # 4. React 빌드 파일 배포
    - name: Deploy React to Server
      run: |
        scp -r frontend/build/* uran@223.130.157.164:/var/www/html/
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}

    # 5. Spring Boot 실행 (원격 서버)
    - name: Deploy and Run Spring Boot on Server
      run: |
        ssh -o StrictHostKeyChecking=no uran@223.130.157.164 << 'EOF'
        cd /home/uran/SmOne/backend # Spring Boot 경로로 이동
        nohup java -jar target/smone-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
        EOF
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
